### ISSUE TITLE
Python error while making Netsol JCL

### ISSUE THREAD

**Issue by EE-EE-EE-EE-EE** [mainframed/ANSi2EBCDiC#3]
When I run: `app/bin/python3 ansi2ebcdic.py --netsol ../test.ans`
I get: 

```
[+] ANSi to EBCDiC Starting
[+] Arguments:

    ANSi File:  ../test.ans
    Type:               TK4- NETSOL (VTAM)
    Jobname:    AWESOME
    Dataset:    ANSI.ART
    Member:             ANSIART
    Cursor: (IC)
        Location:       23,20
        Input length:   20
        Input Color:    RED

[+] ANSi File Info:

    No ANSi file information available



Traceback (most recent call last):
  File "/home/calum/ANSi2EBCDiC/ansi2ebcdic.py", line 1647, in <module>
    ANSITN3270(ansifile=args.ansi_file,
  File "/home/calum/ANSi2EBCDiC/ansi2ebcdic.py", line 1099, in __init__
    self.generate_output()
  File "/home/calum/ANSi2EBCDiC/ansi2ebcdic.py", line 1104, in generate_output
    self.ansi_state_machine(self.ansi)
  File "/home/calum/ANSi2EBCDiC/ansi2ebcdic.py", line 1508, in ansi_state_machine
    self.parse_escape(escape_sequence, byte)
  File "/home/calum/ANSi2EBCDiC/ansi2ebcdic.py", line 1292, in parse_escape
    debug_buffer += ansi_color_escape_types[sequence] + " "
KeyError: '0t[1'
`

Python Version: Python 3.10.6
ANSI File: https://mega.nz/file/b8EkwLxD#ebDwN2IE1oEUecx1bQJO4lrxLqXQKe13HeELzuwp6i4

**Comment by mainframed** [comment]
Can you rerun it with the debug flag and paste the output here?

`app/bin/python3 ansi2ebcdic.py --netsol --debug ../test.ans`

**Comment by EE-EE-EE-EE-EE** [comment]
[+] ANSi to EBCDiC Starting
[+] Arguments:

    ANSi File:  ../test.ans
    Type:               TK4- NETSOL (VTAM)
    Jobname:    AWESOME
    Dataset:    ANSI.ART
    Member:             ANSIART
    Cursor: (IC)
        Location:       23,20
        Input length:   20
        Input Color:    RED

[+] ANSi File Info:

    No ANSi file information available



```DEBUG    :: ansi_state_machine     :: (1,1) Escape Sequence Found
DEBUG    :: parse_escape           :: (1,1) type: m Sequence: 0;40;32 (desc: Set styles and colors from here onwards)
DEBUG    :: parse_escape           :: (1,1) Color Escape Sequence
DEBUG    :: parse_escape           :: (1,1) Normal Display (BG) Black (FG) Green  (SA: 2800002845F02842F4)
DEBUG    :: add_sba                :: (1,1) setting SBA: 1,1
DEBUG    :: add_hlasm              :: (1,1) adding hlasm:
* (1,1) Normal Display (BG) Black (FG) Green
         DC    X'2800002845F02842F4'
DEBUG    :: ansi_state_machine     :: (1,1) Escape Sequence Found
DEBUG    :: ansi_state_machine     :: (1,1) Escape Sequence Found
DEBUG    :: ansi_state_machine     :: (1,1) Escape Sequence Found
DEBUG    :: parse_escape           :: (1,1) type: m Sequence: 0;0;0;0t[1;0;171;0tT[34 (desc: Set styles and colors from here onwards)
DEBUG    :: parse_escape           :: (1,1) Color Escape Sequence```
Traceback (most recent call last):
  File "/home/calum/ANSi2EBCDiC/ansi2ebcdic.py", line 1647, in <module>
    ANSITN3270(ansifile=args.ansi_file,
  File "/home/calum/ANSi2EBCDiC/ansi2ebcdic.py", line 1099, in __init__
    self.generate_output()
  File "/home/calum/ANSi2EBCDiC/ansi2ebcdic.py", line 1104, in generate_output
    self.ansi_state_machine(self.ansi)
  File "/home/calum/ANSi2EBCDiC/ansi2ebcdic.py", line 1508, in ansi_state_machine
    self.parse_escape(escape_sequence, byte)
  File "/home/calum/ANSi2EBCDiC/ansi2ebcdic.py", line 1292, in parse_escape
    debug_buffer += ansi_color_escape_types[sequence] + " "
KeyError: '0t[1'

**Comment by mainframed** [comment]
Could you please edit your comment and replace the entire debug log in a code block, that is, rerun the python and copy and paste the debug log inside a code block (you can use three backticks ``` on their own line and then after the debug log add three more backticks to make a code block).

**Comment by EE-EE-EE-EE-EE** [comment]
I put 3 backticks at the start and end of the debug log however it just put the whole output into a code block

**Comment by mainframed** [comment]
Ok, figured it out, try a new version of the script, here's the change that fixed it https://github.com/mainframed/ANSi2EBCDiC/commit/3102839650afce5e04b12433d9c313810fab4f58

**Comment by wrljet** [comment]
I get this:

```
ill@debian11:~/ANSi2EBCDiC$ source app/bin/activate
(app) bill@debian11:~/ANSi2EBCDiC$ 
(app) bill@debian11:~/ANSi2EBCDiC$ 
(app) bill@debian11:~/ANSi2EBCDiC$ app/bin/python3 ansi2ebcdic.py  --netsol  01_ansi_art.png 
[+] ANSi to EBCDiC Starting
[+] Arguments:

    ANSi File:	01_ansi_art.png
    Type:		TK4- NETSOL (VTAM)
    Jobname:	AWESOME
    Dataset:	ANSI.ART
    Member:		ANSIART
    Cursor: (IC)
	Location:	23,20
	Input length:	20
	Input Color:	RED

[+] ANSi File Info:

    No ANSi file information available



Traceback (most recent call last):
  File "/home/bill/ANSi2EBCDiC/ansi2ebcdic.py", line 1648, in <module>
    ANSITN3270(ansifile=args.ansi_file,
  File "/home/bill/ANSi2EBCDiC/ansi2ebcdic.py", line 1100, in __init__
    self.generate_output()
  File "/home/bill/ANSi2EBCDiC/ansi2ebcdic.py", line 1105, in generate_output
    self.ansi_state_machine(self.ansi)
  File "/home/bill/ANSi2EBCDiC/ansi2ebcdic.py", line 1509, in ansi_state_machine
    self.parse_escape(escape_sequence, byte)
  File "/home/bill/ANSi2EBCDiC/ansi2ebcdic.py", line 1293, in parse_escape
    debug_buffer += ansi_color_escape_types[sequence] + " "
KeyError: 'ó■╖\x06┐╧├3â≈'
(app) bill@debian11:~/ANSi2EBCDiC$
```

**Comment by mainframed** [comment]
Is `01_ansi_art.png` and ANSI art file you can open in something like PabloDraw or Morbeus or is it in image of ansi art?

If it's just a PNG file its not supported.

**Comment by wrljet** [comment]
It's from your repo.

**Comment by mainframed** [comment]
Yeah, thats just an image so the readme looks nice, its not a sample ANSI file.

**Comment by wrljet** [comment]
Oh  :)

**Comment by mainframed** [comment]
If you want a bunch to mess around with check this out: https://github.com/MVS-sysgen/NETSOL/tree/main/ans also the readme has links to the ansi art files used in the screenshots.
